---

test_routes:
  - command: show route summary

  - item:
      xpath: //route-table[table-name='inet.0']
      id: ./table-name

      tests:
        - is-gt: total-route-count, 20
          err: "Test Fail!"
          info: "Test Pass!"

  - item:
      xpath: //route-table[table-name='inet.3']
      id: ./table-name

      tests:
        - is-gt: total-route-count, 20
          err: "Test Fail!"
          info: "Test Pass!"

  - item:
      xpath: //route-table[table-name='mpls.0']
      id: ./table-name

      tests:
        - is-gt: total-route-count, 20
          err: "Test Fail!"
          info: "Test Pass!"



